name: Make My Website Map

on:
  push:
    branches:
      - main # This means, when you update your website, the robot starts

jobs:
  make_map:
    runs-on: ubuntu-latest
    steps:
      - name: Get My Website's Stuff
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # so the robot knows when each page was last changed

      - name: Make the Map!
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://www.datatech-mm.com" # Put your website address here!

      - name: Save the Map
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated website map!"
